# Generated by Django 5.2.17 on 2026-09-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platforms',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
