# Generated by Django 5.2.17 on 2026-09-01 15:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_progress_percentage_employeeprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_file', models.FileField(upload_to='deliverables/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='campaigns.campaign')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_deliverables', to='campaigns.employeeprofile')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
