# Generated by Django 5.2.17 on 2026-09-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_product_service_name_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
