# Generated by Django 5.2.17 on 2026-09-19 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('kind', models.CharField(choices=[('comment', 'Message'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='comment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='deliverable',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='campaigns.deliverable'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='deliverable',
            constraint=models.UniqueConstraint(fields=('original', 'version'), name='unique_deliverable_revision'),
        ),
        migrations.AddConstraint(
            model_name='deliverable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('original__isnull', True), ('version', 1)), models.Q(('original__isnull', False), ('version__gte', 2)), _connector='OR'), name='deliverable_version_shape'),
        ),
        migrations.AddField(
            model_name='deliverablemessage',
            name='deliverable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaigns.deliverable'),
        ),
        migrations.AddField(
            model_name='deliverablemessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliverable_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
