# Generated by Django 5.2.17 on 2026-09-23 15:37

import campaigns.file_validation
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_deliverablemessage_deliverable_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='uploaded_file',
            field=models.FileField(upload_to='deliverables/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(('pdf', 'docx', 'jpg', 'jpeg', 'png', 'mp4', 'mov', 'webm')), campaigns.file_validation.validate_deliverable_content]),
        ),
    ]
